/**
 * C-4 contract — Conceptual problem bank type.
 *
 * Lives in its own file (NOT in src/content/types.ts) to avoid the shared-file
 * collision with the practice-redesign workstream (see f2-build-plan.md §"The one rule").
 *
 * Part-1 answer is code-verifiable (ExactAnswer).
 * Part-2 "why" is judged by the model against rubricKeyPoints + misconceptions
 * (closed set), never open-endedly.
 */

import type { ExactAnswer } from '../../lib/probability/exact';
import type { MisconceptionKey } from '../misconceptions';
import type { SkillId, Topic } from '../skills';

export type ConceptualProblem = {
  id: string;
  prompt: string;
  /** Practice topic this problem belongs to — used to interleave it with the
   *  matching-topic template problems in the practice loop. */
  topic: Topic;
  /** Skills exercised — feeds the per-skill learner model on resolution. */
  skills: SkillId[];
  /** Part 1 — code-verified answer. */
  answer: ExactAnswer;
  /** Part 2 — what a correct "why" must hit (used as rubric for model judgment). */
  rubricKeyPoints: string[];
  /** Closed set — only keys from MisconceptionKey; model classifies against these, never invents. */
  misconceptions: MisconceptionKey[];
  /** Shown on reveal (loaded from bank, NOT generated by the model). */
  canonicalWhy: string;
};
